services:
  storage-service:
    container_name: storage-service
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      - ./settings.xml:/root/.m2/settings.xml
    depends_on:
      - minio_storage
      - db_storage
    networks:
      - dokploy-network

  db_storage:
    container_name: db_storage
    image: postgres:latest
    environment:
      POSTGRES_DB: cfstorage
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - "$HOME/cf-data/postgres/storage:/var/lib/postgresql"
    ports:
      - "5434:5432"
    networks:
      - dokploy-network

  minio_storage:
    container_name: minio_storage
    image: minio/minio:latest
    volumes:
      - "$HOME/cf-data/minio/storage:/data"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: dockeradmin
      MINIO_ROOT_PASSWORD: dockeradmin
    networks:
      - dokploy-network

volumes:
  cf-data:

networks:
  dokploy-network:
    external: true