spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: storage-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka